### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by GerdP** [hhtznr/JOSM-Elevation-Plugin#2]
See JOSM ticket 23653: https://josm.openstreetmap.de/ticket/23653
Seems the plugin tries to remove an element while iterating over the collection.

**Comment by hhtznr** [comment]
This bug should be fixed with [Release 0.10.1](https://github.com/hhtznr/JOSM-Elevation-Plugin/releases/tag/v0.10.1) which uses an iteration that should not be affected by entries being removed.
